### ISSUE TITLE
Scroll the chat down automatically when chat card extends

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#128]
When the chat card extends (due to rolling, rerolling, etc.) the bottom of the card is hidden because it gets bigger but the chat doesn't scroll down. This is also a problem when using direct roll options. The Chat should scroll down accordingly to show the full card
The autoscroll should have a threshold so that it does _not_ scroll down when the user is viewing older entries of the chat.

**Comment by javierriveracastro** [comment]
That sounds difficult, but we'll see

**Comment by SalieriC** [comment]
Maybe we can borrow some code from [Chat Scrolling](https://foundryvtt.com/packages/chat-scrolling/)?

**Comment by javierriveracastro** [comment]
Now, when you modify the last chat card, it will scroll the chat to the bottom. I hope that this solves the issue. 

If it doesn't, just reopen it.

**Comment by SalieriC** [comment]
Doesn't seem to work with (direct) rolls from non-GMs, rolls from me as GM however seem to scroll down.

**Comment by javierriveracastro** [comment]
The idea was that it only scrolled the chat for the person rolling.

I have committed an update. Now it is much more aggressive. It will scroll everyone char, unless the are far above the last message.

Can you check it?

**Comment by javierriveracastro** [comment]
I will close it for a while.

**Comment by flyingsquad** [comment]
This is still a problem for me. When the damage is rolled, for a card either I or a player generated, the card grows larger but doesn't scroll up  so I can easily click the Apply Damage button. I have to manually scroll the chat **every time** a target is damaged so I can see the button.

Also, it would be nice if there was a setting that would collapse Modifiers for Better Rolls at the bottom of the chat window when Foundry starts up, to make more room in the chat for cards. I rarely use the modifiers, and would prefer to have the extra chat history visible.

**Comment by javierriveracastro** [comment]
Please, open different issues for different problems. This is not a forum or a chat, but more like a shared ToDo list.

But anyway, there is already an option to start with the modifiers collapsed, check the "User" tab in general settings.

Scrolling the chat has changed in Foundry itself, I will take a look.
