### ISSUE TITLE
Add Size/Scale p106 SWADE to the Modifiers

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#201]
Hi.

Can you add the Size/Scale rule to br2?

I have an macro you could if you want: <https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Savage%20Worlds/SizeScaleCalculator.js>

![image](https://user-images.githubusercontent.com/4999783/119150744-1beceb80-ba25-11eb-9591-889fec8c68f0.png)

**Comment by javierriveracastro** [comment]
That will be a great addition

**Comment by SalieriC** [comment]
It shouldn't necessarily be automated though as Swat would screw with that a lot, especially since it doesn't get applied to all actions.

**Comment by CyrilRonseaux** [comment]
The numbers in the screenshot of original post are wrong (discussed in Discord Savage Worlds Server).
It's using the Size difference instead of the **Scales**.

Cat vs Human is +/-4
Human vs Bull is 0
Human vs Dragon is +/-4 

I find it easier to use the Size Table p179 (it lists both the Size and Scale, names and modifiers)

**Comment by brunocalado** [comment]
> The numbers in the screenshot of original post are wrong (discussed in Discord Savage Worlds Server).
> It's using the Size difference instead of the **Scales**.
> 
> Cat vs Human is +/-4
> Human vs Bull is 0
> Human vs Dragon is +/-4
> 
> I find it easier to use the Size Table p179 (it lists both the Size and Scale, names and modifiers)

I think I fixed after we talked

I updated the macro. You can test downloading from the link

**Comment by CyrilRonseaux** [comment]
Oh, no, I didn't mean the macro was incorrect. I mean the original post has not been updated and is incorrect.
I don't need the macro myself. I want to make sure Javier uses the right formula when/if he implements it in BR2.
(I'm working on design and specs, I don't look much in the code :( )

**Comment by javierriveracastro** [comment]
OK, I thing part 1 done (it still doesn't look for swat, but I have added it as a translatable string so it can be done in future versions).

I said "think" because I'm not sure about what you are doing in calc. I mean, is the modifier not just ```targetModifier - actorModfifer```?. Or am I forgetting something?

**Comment by brunocalado** [comment]
Hi.

```js
let actorModifier = sizeToModifier(actorSize); // gets the modifier from page 179
let targetModifier = sizeToModifier(targetSize); // gets the modifier from page 179
```
![image](https://user-images.githubusercontent.com/4999783/125101547-b4602d80-e0b0-11eb-8810-5bb60b935bbf.png)

```js
let modifier = calc(actorModifier, targetModifier); // math from page 106
```
```page 106
When creatures of different Scales attack
each other, the smaller creature adds the
difference between its Scale and its target to
its attacks. A Tiny fairy (−6 Scale modifier),
for example, adds +10 to hurl a bolt at a Huge
dragon (+4).
```

So, the macro

1. Gets the modifier from the table p179
2. Use each creature modifier to calculate the bonus p106

```js
    function calc(actorModifier, targetModifier) {
        let diff;
        if (actorModifier == targetModifier) {
            return 0;
        } else {
            if (actorModifier < targetModifier) {
                diff = Math.abs(actorModifier) + Math.abs(targetModifier);
                return diff;
            } else {
                diff = Math.abs(actorModifier) + Math.abs(targetModifier);
                return -diff;
            }
        }
    }
```

**Comment by javierriveracastro** [comment]
Yes, a Dragon (+4) - faery (-6) = + 10, that is the same result for your calc function and  targetModificier - actorModifier.

The difference is when a Dragon (+4) attacks a Rinho (+2). My calculation gets -2 (2 - 4), but yours yields -6.

**Comment by brunocalado** [comment]
Oh, boy. Is it wrong? I'll check it out. I asked around in the discord to people check.

**Comment by javierriveracastro** [comment]
Well, I have not tried it, this is just from reading the code. I could be easily wrong. But it -2 is the correct modifier then this is done.

**Comment by brunocalado** [comment]
I'm testing. Give me a little time.

![image](https://user-images.githubusercontent.com/4999783/125108999-29cffc00-e0b9-11eb-8296-b8ee81f9ae54.png)

**Comment by javierriveracastro** [comment]
Oh, for this bug that your macro works or not is not really relevant. If I can substitute cal with simple subtraction, the better. Anyway I did use most of your code and you did the thinking for me, so thank you a lot.

And I'm still interested in the result of your test, so post them here please, even if the bug remains closed.

**Comment by brunocalado** [comment]
I updated the macro and create a debug function:
![image](https://user-images.githubusercontent.com/4999783/125113909-a36ae880-e0bf-11eb-99c1-f04786d5c60b.png)

You can add more tests if you want on it:
```js
  // actorSize > targetSize
  actorSize = -3; // Very Small eagle
  targetSize = -4; // Tiny fairy
  output = sizeCalculator(actorSize, targetSize);
  console.log("Very Small eagle " + actorSize + " attacks Tiny fairy " + targetSize + ': ' + output);
```



It maybe be possible to make this function smaller. But, I couldn't find a way. I tried to make it more clear now.
```js
  function sizeCalculator(actorSize, targetSize) { // Mach from page 106 core
    let actorModifier = sizeToModifier(actorSize);
    let targetModifier = sizeToModifier(targetSize);

    let diff;
    if (actorSize == targetSize) {
      return 0;
    } else {
      // When creatures of different Scales attack each other, the smaller creature adds the difference between its Scale and its target to its attacks. A Tiny fairy (−6 Scale modifier), for example, adds +10 to hurl a bolt at a Huge dragon (+4).
      if (actorSize < targetSize) {
        diff = Math.abs(actorModifier) + Math.abs(targetModifier);
        return diff;
      // The larger creature subtracts the difference from its attacks. A Very Small eagle (−4) subtracts 2 from its Fighting totals when attacking a Tiny fairy (−6).
      } else { // actorSize > targetSize
        diff = Math.abs(actorModifier) - Math.abs(targetModifier);
        return diff;
      }
    }
  }
```

Macro for download:
[SizeScaleCalculator.zip](https://github.com/javierriveracastro/betteroll-swade/files/6792960/SizeScaleCalculator.zip)

**Comment by CyrilRonseaux** [comment]
First you should call a cat a cat. It's a **scale** modifier.
Then, it really comes down to what Javier wrote: sustract. Single line. Very simple function.
Also I would rename the function to what it returns, that is a Scale to-hit modifier

``` javascript
 function getToHitScaleModifier(actorSize, targetSize) { // Match from page 106 core
    let actorScaleModifier = sizeToScaleModifier(actorSize);
    let targetScaleModifier = sizeToScaleModifier(targetSize);

   return targetScaleModifier - actorScaleModifier;
} 
```

Examples:

Assuming
- Drake (Size 8) → scale +4 
- Orc (Size 1) → scale +0
- Rhino (Size 5) → scale +2
- Eagle (Size -3) → scale -4
- Fairy (Size -4) → scale -6

results in:
- Drake +4 attacks Orc +0 → +0 - +4 = -4
- Drake +4 attacks Rhino +2 → +2 - +4 = -2
- Drake +4 attacks Eagle -4 → -4 - +4 = -8
- Orc +0 attacks Rhino +2 → +2 - +0 = +2
- Eagle -4 attacks Orc +0 → +0 - -4 = +4
- Eagle -4 attacks Drake +4 → +4 - -4 = +8
- Eagle -4 attacks Fairy -6 → -6 - -4 = -2
- Fairy -6 attacks Drake +4 → +4 - -6 = +10

**Comment by brunocalado** [comment]
> First you should call a cat a cat. It's a **scale** modifier.
> Then, it really comes down to what Javier wrote: sustract. Single line. Very simple function.
> Also I would rename the function to what it returns, that is a Scale to-hit modifier
> 
> ```js
>  function getToHitScaleModifier(actorSize, targetSize) { // Match from page 106 core
>     let actorScaleModifier = sizeToScaleModifier(actorSize);
>     let targetScaleModifier = sizeToScaleModifier(targetSize);
> 
>    return targetScaleModifier - actorScaleModifier;
> } 
> ```
> 
> Examples:
> 
> Assuming
> 
> * Drake (Size 8) → scale +4
> * Orc (Size 1) → scale +0
> * Rhino (Size 5) → scale +2
> * Eagle (Size -3) → scale -4
> * Fairy (Size -4) → scale -6
> 
> results in:
> 
> * Drake +4 attacks Orc +0 → +0 - +4 = -4
> * Drake +4 attacks Rhino +2 → +2 - +4 = -2
> * Drake +4 attacks Eagle -4 → -4 - +4 = -8
> * Orc +0 attacks Rhino +2 → +2 - +0 = +2
> * Eagle -4 attacks Orc +0 → +0 - -4 = +4
> * Eagle -4 attacks Drake +4 → +4 - -4 = +8
> * Eagle -4 attacks Fairy -6 → -6 - -4 = -2
> * Fairy -6 attacks Drake +4 → +4 - -6 = +10

You're amazing! Very good!!!!

**Comment by javierriveracastro** [comment]
Ummm... looks like I have some renaming to do ;P.
