### ISSUE TITLE
Various Deadlands weapons not working after update

### ISSUE THREAD

**Issue by DocArcane** [javierriveracastro/betteroll-swade#313]
After I updated BR2 to v2.43 (FVTT 0.8.9) a variety of provided weapons from the Official Deadlands module do nothing when we try to activate them. Specifically the ones I found so that won't trigger a chat card are ...

Winchester '73, Bullard Express, Colt Lightning, Cole Rainmaker, Colt Thunderer, Bow, Rupertus Pepperbox, Spencer, Bayonet, Club, Club War, Knife, Knife Bowie,  and Tomahawk.

**Comment by javierriveracastro** [comment]
As I don't own Deadlands module, I will need much more info to be able to solve this.

Any console errors (hit F12 to see them), look for red text, or if possible a json export of a non-functioning item could help.

**Comment by DocArcane** [comment]
`item_card.js:1397 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of null
    at get_template_from_description (item_card.js:1397)
    at create_item_card (item_card.js:113)
    at item_click_listener (item_card.js:178)
    at HTMLButtonElement.<anonymous> (item_card.js:199)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)`

**Comment by DocArcane** [comment]
`{
  "name": "Winchester ‘73",
  "type": "weapon",
  "img": "modules/deadlands-core-rules/assets/art/weapons/DLWW_Rifle.webp",
  "data": {
    "description": null,
    "notes": "",
    "additionalStats": {},
    "quantity": 1,
    "weight": 10,
    "price": 25,
    "equippable": true,
    "equipped": false,
    "isVehicular": false,
    "mods": 1,
    "actions": {
      "skill": "Shooting",
      "skillMod": "",
      "dmgMod": "",
      "additional": {}
    },
    "damage": "2d8-1",
    "range": "24/48/96",
    "rof": "1",
    "ap": "2",
    "minStr": "d6",
    "shots": "15",
    "currentShots": "0",
    "ammo": "Rifle Ammunition (Small)",
    "autoReload": false
  },
  "effects": [],
  "sort": 0,
  "flags": {
    "cf": null,
    "swadesfxvfx": {
      "tokenMagicData": {
        "macrosToken": "",
        "macroTokenDelay": "",
        "macroTokenDuration": "",
        "macrosTarget": "",
        "macroTargetDelay": "",
        "macroTargetAnimationDuration": false,
        "macroTargetDuration": ""
      },
      "animationTemplate": "",
      "animationDelay": "",
      "audioTemplate": "",
      "audioDelay": ""
    },
    "exportSource": {
      "world": "deadlands",
      "system": "swade",
      "coreVersion": "0.8.9",
      "systemVersion": "0.20.4"
    }
  }
}`

**Comment by javierriveracastro** [comment]
Ok. Weapons with null descriptions. That is a bug that was introduced with template extraction but it is (or it should) be solved in git. I should probably make a release just with it, as this week (again) I will have little time to work on br.

You just need to edit the description, type something there (a space will do) and save the item and it will work. Afterwards even deleting the space should keep it working.

**Comment by DocArcane** [comment]
I took your advice and added some test to the weapon notes and that fixed those items -- but I am still have some weird issues. This time on brand new items I'm creating... getting this error on a claw attack

`Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
[Detected 1 package: betterrolls-swade2]
    at calculate_gangUp (skill_card.js:436)
    at get_tn_from_token (skill_card.js:279)
    at roll_trait (cards_common.js:600)
    at roll_item (item_card.js:678)
    at async HTMLButtonElement.<anonymous> (item_card.js:276)`

**Comment by javierriveracastro** [comment]
That should also be addressed in next version. I hope, if works allow me, to release it this afternoon (6 or 7 hours from now)

**Comment by DreamingPhantasm** [comment]
Just found that the weapons listed here all broke upon creating a global action with the "item_description_includes" selector - and they also were fixed upon adding the space to their description. They worked fine before the global action being written, so clearly the selector itself doesn't like null descriptions. New items with blank descriptions and many others like generic "Claw/Bite"s seem to work fine, however.

**Comment by javierriveracastro** [comment]
Should be again solved in git.
