### ISSUE TITLE
reload no longer works

### ISSUE THREAD

**Issue by Raileth** [javierriveracastro/betteroll-swade#93]
In the latest version (1.111) pressing reload now causes an error - typeError: cannot 'read' property data of null.

Steps to recreate:-

add weapon to token
fire several shots
press reload using better rolls2
enter bullets to reload
error occurs

**Comment by javierriveracastro** [comment]
Probably caused by trying to support the new ammo thing. I'll try to solve it ASAP.

**Comment by Raileth** [comment]
wow - quick response - love the module by the way

**Comment by Yalnin** [comment]
If you have the new "ammo from bagpack" activated in your settings, you need to have an ammo item in the inventory where it takes the loaded ammo from.  I got this error when the ammo item in the inventory was "empty", i.e. no more ammo left.

**Comment by javierriveracastro** [comment]
I believe this will happen even with "ammo from bagpack" deactivated. Anyway I'll look into it this afternoon and try to make a quick release to address it.

**Comment by SalieriC** [comment]
At the same time you could make it optional to the option as well, so that it doesn't show up when it it deactivated and I can continue using my macro with SFX. :D

**Comment by Raileth** [comment]
its worth noting that with the ammo option enabled it works but it reduces the amount of ammunition by the amount the character specifies even if the gun cant take that amount. e.g a gun with a 12 shots that has fired 2 - if it is reloaded with 12 shots it reduces the ammo by 12 but the amount loaded in the gun is restricted by the max amount. i.e. only 2 shots. - this may be intentional but thought it was worth pointing out if you are looking at it

**Comment by javierriveracastro** [comment]
"optional to the option". Sorry I don't understand. You mean that I respect the system setting?. If it, yes it is a valid bug.

For macro support go to the "Global actions" bug and ask there to add an action to execute a macro. I feel that this is the right place.

**Comment by javierriveracastro** [comment]
This is a multi-bug issue. I'll try to solve all today after work. Now let me solve real bugs!!!. The ones that I get paid to.

**Comment by javierriveracastro** [comment]
All of this should be solved (unless I miss something). Didn't use the system setting at last. Just keep the ammo field empty if you don't want to use it.

SalieriC, now I get you. I'll make a setting about ammo management.

**Comment by Yalnin** [comment]
One little remark here: It still does not work if there is a bracket ( or ) in the ammo item name. I had the calibre in every of my ammo items between brackets except on arrows. This arrow ammo item was the only none that worked, so I figured it out. Removed the brackets on the other ammo items and then it reduced the loaded ammo from them.

**Comment by javierriveracastro** [comment]
I'm going to reopen this, but please next time open a new issue, as people subscribed to this can be not interested in the new one. Also it's easier to my to find things pending.

**Comment by javierriveracastro** [comment]
It does work for me. It must be something else. Can you tell me the exact name of you ammo.

**Comment by Yalnin** [comment]
Call me crazy, I could not reproduce the problem again. Yesterday I experienced this effect several times.

"Patronen (9mm)" - did not work
"Patronen 9mm" - worked

Now both work... Maybe it was interference with something else. I switched even languages to make sure it was not a matter of changed keyboard layouts...

Tonight I will have an extensive testing night of the new ammo system with my players, but in the moment I can not repoduce the problem. Sorry for the time waste - I think you can close the case, if I can reproduce it again I will open a new topic.

**Comment by javierriveracastro** [comment]
Ok, closing it.
